//   Aggregate Functions

// 1:

SELECT ORDERS.ORDER_ID, USERS.USER_ID, ORDERS.STORE_ID 
FROM ORDERS
JOIN USERS ON USERS.USER_ID = ORDERS.USER_ID
WHERE FIRST_NAME LIKE 'Marion';

//  2:

SELECT ORDERS.ORDER_ID, USERS.USER_ID, ORDERS.STORE_ID, ORDER_ITEMS.QUANTITY
FROM ORDERS
JOIN USERS ON USERS.USER_ID = ORDERS.USER_ID
JOIN ORDER_ITEMS ON ORDER_ITEMS.ORDER_ID = ORDERS.ORDER_ID
WHERE ORDER_ITEMS.QUANTITY < 1;

// There are no users with a 0 quantity in ORDER_ITEMS


//  3:

SELECT DISTINCT ITEMS.NAME, ITEMS.PRICE
FROM ITEMS
JOIN ORDER_ITEMS ON ORDER_ITEMS.ITEM_ID = ITEMS.ITEM_ID
WHERE ORDER_ITEMS.QUANTITY > 1;


// 4:


