//   Aggregate Functions

// 1:

SELECT ORDERS.ORDER_ID, USERS.USER_ID, ORDERS.STORE_ID 
FROM ORDERS
JOIN USERS ON USERS.USER_ID = ORDERS.USER_ID
WHERE FIRST_NAME LIKE 'Marion';

//  2:

SELECT ORDERS.ORDER_ID, USERS.USER_ID, ORDERS.STORE_ID, ORDER_ITEMS.QUANTITY
FROM ORDERS
JOIN USERS ON USERS.USER_ID = ORDERS.USER_ID
JOIN ORDER_ITEMS ON ORDER_ITEMS.ORDER_ID = ORDERS.ORDER_ID
WHERE ORDER_ITEMS.QUANTITY < 1;

// There are no users with a 0 quantity in ORDER_ITEMS


//  3:

SELECT DISTINCT ITEMS.NAME, ITEMS.PRICE
FROM ITEMS
JOIN ORDER_ITEMS ON ORDER_ITEMS.ITEM_ID = ITEMS.ITEM_ID
WHERE ORDER_ITEMS.QUANTITY > 1;


// 4:

SELECT DISTINCT ITEMS.NAME AS 'ITEM_NAME', (ORDER_ITEMS.QUANTITY * ITEMS.PRICE) AS 'REVENUE'
FROM ITEMS
JOIN ORDER_ITEMS ON ORDER_ITEMS.ITEM_ID = ITEMS.ITEM_ID
WHERE ORDER_ITEMS.QUANTITY != 0
GROUP BY REVENUE DESC;


//  5:

// STILL WORKING ON THIS ONE

SELECT DISTINCT STORES.NAME, ORDERS.STORE_ID AS 'Order Quantity' , STORES.STORE_ID AS 'Sales Figures' 
FROM STORES, ORDERS
//JOIN ORDER_ITEMS ON ORDER_ITEMS.ITEM_ID = ITEMS.ITEM_ID
//WHERE ORDER_ITEMS.QUANTITY != 0
//GROUP BY REVENUE DESC;

// STILL WORKING ON THIS ONE


